package com.capgimini.ExceptionEx;


	public class Test {

		public static void main(String[] args) {
	  
	      int arr[]=new int[7];
	      
	      try {
			arr[10]=arr[11];
			
//		} catch (ArithmeticException e) {
//			e.printStackTrace();
//		}
//	      catch (ArrayIndexOutOfBoundsException e) {
//	  		e.printStackTrace();
	   }
	      catch (Exception e) {
	    		e.printStackTrace();
	        }
	              
	               
	      System.out.println("Print Me");
	   
				
			
	}
		
	}



